### ISSUE TITLE
New release for Grails 3.3.9 ?

### ISSUE THREAD

**Issue by aadrian** [uberall/grails-executor#2]
Hi,

Any chance getting a new release of this plug-in for Grails 3.3.9 ?

Thank you.

**Comment by bp-FLN** [comment]
sorry, but we don't maintain this plugin anymore.
reason is that grails 3 has some nice mechanisms build-in for creating threads, so this plugin is not needed anymore. a while ago we replaced all executorService calls with Promises.

see https://github.com/basejump/grails-executor/issues/13

**Comment by aadrian** [comment]
@bp-FLN thanks for the info. Than please mark this project as "read-only" from the GitHub settings.

**Comment by bp-FLN** [comment]
ok, will update readme and archive this repo. thanks
